{
    "name": "Email activity tracking",
    "summary": "Email activity tracking system for all mails sent",
    "version": "17.0.1.0.0",
    "category": "Social Network",
    "website": "https://www.techvoot.com",
    "author": "Techvoot Solutions",
    "license": "AGPL-3",
    "application": False,
    "installable": True,
    "depends": ["mail", "crm"],
    "images": ["static/description/email_activity_tracking.gif"],
    "data": [
        "data/tracking_data.xml",
        "security/mail_activity_tracking_security.xml",
        "security/ir.model.access.csv",
        "views/mail_activity_tracking_view.xml",
        "views/mail_activity_event_view.xml",
        "views/mail_message_view.xml",
        "views/res_partner_view.xml",
        "views/crm_lead_view.xml",
        "wizards/res_config_settings_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "mail_activity_tracking/static/src/core/chatter/*",
            "mail_activity_tracking/static/src/core/message/*",
            "mail_activity_tracking/static/src/core/search/*",
            "mail_activity_tracking/static/src/core/discuss/*",
            "mail_activity_tracking/static/src/services/*",
            "mail_activity_tracking/static/src/components/message_tracking/*",
            "mail_activity_tracking/static/src/components/failed_message/*",
            "mail_activity_tracking/static/src/components/failed_message_review/*",
            "mail_activity_tracking/static/src/components/failed_messages_panel/*",
        ],
    },
    "demo": ["demo/demo.xml"],
}
